apiVersion: v1
kind: Service
metadata:
  name: chidhvis-chess
  labels:
    app: chidhvis-chess
spec:
  type: NodePort
  selector:
    app: chidhvis-chess
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
